### ISSUE TITLE
wondering if setstate can be replaced by setting props

### ISSUE THREAD

**Issue by zzz6519003** [clariussystems/react-ios-switch#1]
cuz i heard that it's an anti-pattern XD :beer:

**Comment by mking-clari** [comment]
I think state should be ok for properties that are internal to the component. I found that externalizing animation state makes the app a bit slower. For example, in this component, we keep track of the mouse position. If we store the mouse position in the top level application state, this will result in a lot of unnecessary top level renders. [react-motion](https://github.com/chenglou/react-motion/blob/master/src/components.js) takes the same approach for keeping track of animation properties.

**Comment by zzz6519003** [comment]
thx man! i love react-motion, wondering how those magic happens by just letting you wrap a component , inside it have a anoy func to make magic XD

**Comment by mking** [comment]
ahh yea chenglou is a master, thanks for the feedback

**Comment by mking-clari** [comment]
ahh yea chenglou is a master, thanks for the feedback
